starting-points: 100
points-stolen-on-kill: 20
crystal-break-points: 5
allow-check-others: false
on-zero-points-command: "ban %player% Bạn đã hết điểm và mất quyền công dân!"

#Cooldowns
cooldowns:
  pvp: 30
  crystal: 60
  global: 10