name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Read version from pom.xml
        id: get_version
        run: |
          VERSION=$(xmllint --xpath "string(//project/version)" pom.xml)
          echo "plugin_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn package -B

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.plugin_version }}
          name: PointKing v${{ steps.get_version.outputs.plugin_version }}
          files: target/PointKing-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
